services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: general_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - spring-general
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-general:
    driver: bridge

volumes:
  postgres:
    driver: local