services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: itutorix
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: ubuntu_assist
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: